export const ACTION_NAME = {
  LOGIN_ACTION : {
    LOGIN_ACTION : 'LOGIN_ACTION',
    LOGIN_ACTION_SUCCESS : 'LOGIN_ACTION_SUCCESS',
    LOGIN_ACTION_FAIL : 'LOGIN_ACTION_FAIL'
  },
  SIGNUP_ACTION : {
    SIGNUP_ACTION : 'SIGNUP_ACTION',
    SIGNUP_ACTION_SUCCESS : 'SIGNUP_ACTION_SUCCESS',
    SIGNUP_ACTION_FAIL : 'SIGNUP_ACTION_FAIL'
  }
}