export const ACTION_NAME = {
  LOGIN_ACTION: {
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_ACTION_SUCCESS: 'LOGIN_ACTION_SUCCESS',
    LOGIN_ACTION_FAIL: 'LOGIN_ACTION_FAIL',
  },
  SIGNUP_ACTION: {
    SIGNUP_ACTION: 'SIGNUP_ACTION',
    SIGNUP_ACTION_SUCCESS: 'SIGNUP_ACTION_SUCCESS',
    SIGNUP_ACTION_FAIL: 'SIGNUP_ACTION_FAIL',
    SIGNUP_ACTION_RELOAD: 'SIGNUP_ACTION_RELOAD',
  },
  RECOVERPASSWORD_ACTION: {
    RECOVERPASSWORD_ACTION: 'RECOVERPASSWORD_ACTION',
    RECOVERPASSWORD_ACTION_SUCCESS: 'RECOVERPASSWORD_ACTION_SUCCESS',
    RECOVERPASSWORD_ACTION_FAIL: 'RECOVERPASSWORD_ACTION_FAIL',
  },
  CHANGEPASSWORD_ACTION: {
    CHANGEPASSWORD_ACTION: 'CHANGEPASSWORD_ACTION',
    CHANGEPASSWORD_ACTION_SUCCESS: 'CHANGEPASSWORD_ACTION_SUCCESS',
    CHANGEPASSWORD_ACTION_FAIL: 'CHANGEPASSWORD_ACTION_FAIL',
  },
  LOGIN_WITH_EMAIL_ACTION: {
    LOGIN_WITH_EMAIL_ACTION: 'CHANGEPASSWORD_ACTION',
    LOGIN_WITH_EMAIL_ACTION_SUCCESS: 'LOGIN_WITH_EMAIL_ACTION_SUCCESS',
    LOGIN_WITH_EMAIL_ACTION_FAIL: 'LOGIN_WITH_EMAIL_ACTION_FAIL',
  },
  LOGOUT_ACTION: 'LOGOUT_ACTION',
};
