export const ACTION_NAME = {
  GET_LIST_CAR: {
    GET_LIST_CAR: 'GET_LIST_CAR',
    GET_LIST_CAR_SUCCESS: 'GET_LIST_CAR_SUCCESS',
    GET_LIST_CAR_FAIL: 'GET_LIST_CAR_FAIL',
  },

  GET_LIST_CAR_BY_CATEGORY: {
    GET_LIST_CAR_BY_CATEGORY: 'GET_LIST_CAR_BY_CATEGORY',
    GET_LIST_CAR_BY_CATEGORY_SUCCESS: 'GET_LIST_CAR_BY_CATEGORY_SUCCESS',
    GET_LIST_CAR_BY_CATEGORY_FAIL: 'GET_LIST_CAR_BY_CATEGORY_FAIL',
    GET_LIST_CAR_BY_CATEGORY_RELOAD: 'GET_LIST_CAR_BY_CATEGORY_RELOAD',
  },
};
