export const ACTION_NAME = {
  GET_LIST_CAR: {
    GET_LIST_CAR: 'GET_LIST_CAR',
    GET_LIST_CAR_SUCCESS: 'GET_LIST_CAR_SUCCESS',
    GET_LIST_CAR_FAIL: 'GET_LIST_CAR_FAIL',
  },

  GET_LIST_CAR_BY_CATEGORY: {
    GET_LIST_CAR_BY_CATEGORY: 'GET_LIST_CAR_BY_CATEGORY',
    GET_LIST_CAR_BY_CATEGORY_SUCCESS: 'GET_LIST_CAR_BY_CATEGORY_SUCCESS',
    GET_LIST_CAR_BY_CATEGORY_FAIL: 'GET_LIST_CAR_BY_CATEGORY_FAIL',
    GET_LIST_CAR_BY_CATEGORY_RELOAD: 'GET_LIST_CAR_BY_CATEGORY_RELOAD',
  },

  GET_LIST_CAR_BY_PRICE: {
    GET_LIST_CAR_BY_PRICE: 'GET_LIST_CAR_BY_PRICE',
    GET_LIST_CAR_BY_PRICE_SUCCESS: 'GET_LIST_CAR_BY_PRICE_SUCCESS',
    GET_LIST_CAR_BY_PRICE_FAIL: 'GET_LIST_CAR_BY_PRICE_FAIL',
    GET_LIST_CAR_BY_PRICE_RELOAD: 'GET_LIST_CAR_BY_PRICE_RELOAD',
  },

  GET_LIST_NEWCAR: {
    GET_LIST_NEWCAR_SUCCESS: 'GET_LIST_NEWCAR_SUCCESS',
    GET_LIST_NEWCAR_FAIL: 'GET_LIST_NEWCAR_FAIL',
  },

  GET_LIST_TOPCHOICE: {
    GET_LIST_TOPCHOICE_SUCCESS: 'GET_LIST_TOPCHOICE_SUCCESS',
    GET_LIST_TOPCHOICE_FAIL: 'GET_LIST_TOPCHOICE_FAIL',
  },

  GET_LIST_SALEOFF: {
    GET_LIST_SALEOFF_SUCCESS: 'GET_LIST_SALEOFF_SUCCESS',
    GET_LIST_SALEOFF_FAIL: 'GET_LIST_SALEOFF_FAIL',
  },
};
