export const ACTION_NAME = {
  GET_LIST_COMMENT: {
    GET_LIST_COMMENT_SUCCESS: 'GET_LIST_COMMENT_SUCCESS',
    GET_LIST_COMMENT_FAIL: 'GET_LIST_COMMENT_FAIL',
  },
  RELOAD_ADD_COMMENT: 'RELOAD_ADD_COMMENT',
  ADD_COMMENT: {
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAIL: 'ADD_COMMENT_FAIL',
  },
};
