export const ACTION_NAME = {
  ADD_ITEM_ACTION: {
    ADD_ITEM_ACTION: 'ADD_ITEM_ACTION',
    ADD_ITEM_ACTION_SUCCESS: 'ADD_ITEM_ACTION_SUCCESS',
    ADD_ITEM_ACTION_FAIL: 'ADD_ITEM_ACTION_FAIL',
  },
  REMOVE_ITEM_ACTION: {
    REMOVE_ITEM_ACTION: 'REMOVE_ITEM_ACTION',
    REMOVE_ITEM_ACTION_SUCCESS: 'REMOVE_ITEM_ACTION_SUCCESS',
    REMOVE_ITEM_ACTION_FAIL: 'REMOVE_ITEM_ACTION_FAIL',
  },
  RELOADED_LIST: 'RELOADED_LIST',
};
