export const ACTION_NAME = {
  ADD_ITEM_ACTION: {
    ADD_ITEM_ACTION: 'ADD_ITEM_ACTION',
    ADD_ITEM_ACTION_SUCCESS: 'ADD_ITEM_ACTION_SUCCESS',
    ADD_ITEM_ACTION_FAIL: 'ADD_ITEM_ACTION_FAIL',
  },
  ADD_COLOR_ACTION: {
    ADD_COLOR_ACTION: 'ADD_COLOR_ACTION',
    ADD_COLOR_ACTION_SUCCESS: 'ADD_COLOR_ACTION_SUCCESS',
    ADD_COLOR_ACTION_FAIL: 'ADD_COLOR_ACTION_FAIL',
  },
  UPDATE_ITEM_ACTION: {
    UPDATE_ITEM_ACTION: 'UPDATE_ITEM_ACTION',
    UPDATE_ITEM_ACTION_SUCCESS: 'UPDATE_ITEM_ACTION_SUCCESS',
    UPDATE_ITEM_ACTION_FAIL: 'UPDATE_ITEM_ACTION_FAIL',
  },
  UPDATE_QUANTITY_ACTION: {
    UPDATE_QUANTITY_ACTION: 'UPDATE_QUANTITY_ACTION',
    UPDATE_QUANTITY_ACTION_SUCCESS: 'UPDATE_QUANTITY_ACTION_SUCCESS',
    UPDATE_QUANTITY_ACTION_FAIL: 'UPDATE_QUANTITY_ACTION_FAIL',
  },
  REMOVE_ITEM_ACTION: {
    REMOVE_ITEM_ACTION: 'REMOVE_ITEM_ACTION',
    REMOVE_ITEM_ACTION_SUCCESS: 'REMOVE_ITEM_ACTION_SUCCESS',
    REMOVE_ITEM_ACTION_FAIL: 'REMOVE_ITEM_ACTION_FAIL',
  },
  RELOADED_LIST: 'RELOADED_LIST',
};
