export const ACTION_NAME = {
  GET_LIST_CATEGORY: {
    GET_LIST_CATEGORY: 'GET_LIST_CATEGORY',
    GET_LIST_CATEGORY_SUCCESS: 'GET_LIST_CATEGORY_SUCCESS',
    GET_LIST_CATEGORY_FAIL: 'GET_LIST_CATEGORY_FAIL',
  },
};
