export const STATUS = {
  SUCCESS: 'SUCCESS',
  FAIL: 'FAIL',
  NONE: 'NONE',
};

export const STATUS_LOGOUT = {
  SUCCESS: 'LOGOUT_SUCCESS',
  FAIL: 'LOGOUT_FAIL',
};

export const STATUS_SIGNUP = {
  SUCCESS: 'SIGNUP_SUCCESS',
  FAIL: 'SIGNUP_FAIL',
  NONE: 'SIGNUP_NONE',
};
