export const ACTION_NAME = {
  GET_LIST_CART_ACTION: {
    GET_LIST_CART_SUCCESS: 'GET_LIST_CART_SUCCESS',
    GET_LIST_CART_FAIL: 'GET_LIST_CART_FAIL',
  },

  DELETE_CART_ACTION: {
    DELETE_CART_ACTION_SUCCESS: 'DELETE_CART_ACTION_SUCCESS',
    DELETE_CART_ACTION_FAIL: 'DELETE_CART_ACTION_FAIL',
  },
};
