export const ACTION_NAME = {
  GET_INT_MESSAGE: {
    GET_INT_MESSAGE: 'GET_INT_MESSAGE',
    GET_INT_MESSAGE_SUCCESS: 'GET_INT_MESSAGE_SUCCESS',
    GET_INT_MESSAGE_FAIL: 'GET_INT_MESSAGE_FAIL',
  },
  SEND_MESSAGE: {
    SEND_MESSAGE: 'SEND_MESSAGE',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAIL: 'SEND_MESSAGE_FAIL',
  },
};
