export const ACTION_NAME = {
  CREATE_PAYMENT: {
    CREATE_PAYMENT: 'CREATE_PAYMENT',
    CREATE_PAYMENT_SUCCESS: 'CREATE_PAYMENT_SUCCESS',
    CREATE_PAYMENT_FAIL: 'CREATE_PAYMENT_FAIL',
  },
  SET_STATUS_DEFAULT: 'SET_STATUS_DEFAULT',
};
