export const ACTION_NAME = {
  GET_STORE_INFO: {
    GET_STORE_INFO: 'GET_STORE_INFO',
    GET_STORE_INFO_SUCCESS: 'GET_STORE_INFO_SUCCESS',
    GET_STORE_INFO_FAIL: 'GET_STORE_INFO_FAIL',
  },
  EDIT_STORE_INFO: {
    EDIT_STORE_INFO: 'EDIT_STORE_INFO',
    EDIT_STORE_INFO_SUCCESS: 'EDIT_STORE_INFO_SUCCESS',
    EDIT_STORE_INFO_FAIL: 'EDIT_STORE_INFO_FAIL',
  },
};
