export const ACTION_NAME = {
  BOOKING_ACTION: {
    BOOKING_SUCCESS: 'BOOKING_SUCCESS',
    BOOKING_FAIL: 'BOOKING_FAIL',
    BOOKING_CHANGE_MODAL: 'BOOKING_CHANGE_MODAL',
    CANCEL_BOOKING_SUCCESS: 'CANCEL_BOOKING_SUCCESS',
    CANCEL_BOOKING_FAIL: 'CANCEL_BOOKING_FAIL',
  },
};
