export const ACTION_NAME = {
  BOOKING_ACTION: {
    BOOKING_SUCCESS: 'BOOKING_SUCCESS',
    BOOKING_FAIL: 'BOOKING_FAIL',
    BOOKING_CHANGE_MODAL: 'BOOKING_CHANGE_MODAL',
    CANCEL_BOOKING_SUCCESS: 'CANCEL_BOOKING_SUCCESS',
    CANCEL_BOOKING_FAIL: 'CANCEL_BOOKING_FAIL',
    CONFIRM_BOOKING_SUCCESS: 'CONFIRM_BOOKING_SUCCESS',
    CONFIRM_BOOKING_FAIL: 'CONFIRM_BOOKING_FAIL',
    GET_LIST_MEETINGS_SUCCESS: 'GET_LIST_MEETINGS_SUCCESS',
    GET_LIST_MEETINGS_FAIL: 'GET_LIST_MEETINGS_FAIL',
  },
};
